/**
 * One-time / occasional sync: uploads public/videos, public/images, src/images to Vercel Blob
 * and writes src/generated/blob-media.ts. Requires BLOB_READ_WRITE_TOKEN in .env or .env.local.
 */
import { createReadStream, statSync } from 'node:fs'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, posix, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

import { put } from '@vercel/blob'
import { globSync } from 'fast-glob'
import { config } from 'dotenv'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

config({ path: join(root, '.env.local') })
config({ path: join(root, '.env') })

if (!process.env.BLOB_READ_WRITE_TOKEN) {
  console.error('Missing BLOB_READ_WRITE_TOKEN. Add it to .env.local or .env and retry.')
  process.exit(1)
}

const BLOB_PREFIX = 'media'

type Job = { absPath: string; key: string; pathname: string }

function collectJobs(): Job[] {
  const jobs: Job[] = []

  const videoFiles = globSync('videos/**/*', {
    cwd: join(root, 'public'),
    absolute: true,
    onlyFiles: true,
  })
  for (const abs of videoFiles) {
    const rel = relative(join(root, 'public'), abs)
    const key = rel.split(/[/\\]/).join('/')
    jobs.push({ absPath: abs, key, pathname: posix.join(BLOB_PREFIX, key) })
  }

  const publicImages = globSync('images/**/*', {
    cwd: join(root, 'public'),
    absolute: true,
    onlyFiles: true,
  })
  for (const abs of publicImages) {
    const rel = relative(join(root, 'public'), abs)
    const key = rel.split(/[/\\]/).join('/')
    jobs.push({ absPath: abs, key, pathname: posix.join(BLOB_PREFIX, key) })
  }

  const bundled = globSync('images/**/*', {
    cwd: join(root, 'src'),
    absolute: true,
    onlyFiles: true,
  })
  for (const abs of bundled) {
    const rel = relative(join(root, 'src', 'images'), abs)
    const key = `bundled/${rel.split(/[/\\]/).join('/')}`
    jobs.push({ absPath: abs, key, pathname: posix.join(BLOB_PREFIX, key) })
  }

  return jobs
}

async function main() {
  const jobs = collectJobs()
  const manifest: Record<string, string> = {}

  console.log(`Uploading ${jobs.length} files…`)

  for (const { absPath, key, pathname } of jobs) {
    const size = statSync(absPath).size
    const useMultipart = size > 4_000_000
    const body = useMultipart ? createReadStream(absPath) : readFileSync(absPath)

    const result = await put(pathname, body, {
      access: 'public',
      addRandomSuffix: false,
      allowOverwrite: true,
      multipart: useMultipart,
    })

    manifest[key] = result.url
    console.log(pathname)
  }

  const keys = Object.keys(manifest).sort()
  const lines = keys.map(
    (k) => `  ${JSON.stringify(k)}: ${JSON.stringify(manifest[k])},`
  )

  const out = `/* oxlint-disable */
/**
 * Generated by scripts/upload-media-to-blob.ts — do not edit by hand.
 * Re-run: pnpm upload-media
 */
export const blobMedia = {
${lines.join('\n')}
} as const

export type BlobMediaKey = keyof typeof blobMedia
`

  const outPath = join(root, 'src', 'generated', 'blob-media.ts')
  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, out, 'utf8')
  console.log(`\nWrote ${outPath}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
